#!/bin/bash

# joekamprad on sway screenshot helper:
# needed packages: `sudo pacman -Syu grim slurp swappy`
# this tool let you seleczt rectangle area of your screen, 
# opens it in swappy to edit, and save it under users screenshot path.

DIR="$(xdg-user-dir PICTURES)/screenshots"
mkdir -p "$DIR"
FILENAME="screenshot_$(date '+%Y-%m-%d_%H-%M-%S').png"
TARGET="$DIR/$FILENAME"

# tmp file
TMPFILE="/tmp/swappy_$$.png"

# take screenshot and save as tmp
grim -g "$(slurp)" "$TMPFILE"

# open in swappy
swappy -f "$TMPFILE"

# checking if swappy saved something
# usually under $HOME/  directly
LATEST=$(ls -t "$HOME"/swappy-*.png 2>/dev/null | head -n1)

if [ -f "$LATEST" ]; then
    mv "$LATEST" "$TARGET"
    notify-send "Screenshot saved" "$TARGET"
    echo "Saved under: $TARGET"
else
    notify-send "Screenshot canceled or not saved"
    echo "No screenshot saved."
fi

# cleanup
rm -f "$TMPFILE"
