#!/bin/bash

# joekamprad on sway screencast helper (swaycast):
# needed packages: `sudo pacman -Syu --needed slurp wl-screenrec xdg-user-dirs`
# wl-screenrec currently only in AUR will beadded to EndeavourOS repo in case of release
# this tool let you select rectangle area of your screen [$mod+shift+y],and start recording that area. 
# to stop press [$mod+shift+x] it will save automatically to video $HOME dir.

VIDEOS_DIR=$(xdg-user-dir VIDEOS 2>/dev/null)
if [ -z "$VIDEOS_DIR" ]; then
  VIDEOS_DIR="$HOME/Videos"
fi

DIR="$VIDEOS_DIR/screencasts"
mkdir -p "$DIR"
FILENAME="screencast_$(date '+%Y-%m-%d_%H-%M-%S').mp4"
TARGET="$DIR/$FILENAME"

# ASelect recording area
GEOM=$(slurp)

# start recording (in the background)
wl-screenrec -g "$GEOM" -f "$TARGET" &
PID=$!

notify-send -i media-record "Screencast running" "stop with: kill $PID"

# PID gets saved to be used for stop script
echo $PID > /tmp/wl-screenrec.pid
