#!/bin/bash

# joekamprad on sway screencast helper (swaycast):
# screencast-stop part for screencast-select

PID=$(cat /tmp/wl-screenrec.pid 2>/dev/null)
if [ -n "$PID" ]; then
  kill "$PID"
  notify-send -i media-playback-stop "Screencast stopped"
else
  notify-send -i dialog-error "No running Screencast found"
fi
