#!/usr/bin/env bash

# swaycast - Screencast helper for Sway
# Copyright (C) 2025 Johannes Kamprad
# SPDX-License-Identifier: GPL-3.0-or-later

# needed packages: `sudo pacman -Syu --needed slurp wl-screenrec xdg-user-dirs`
# wl-screenrec currently only in AUR will be added to EndeavourOS repo in case of release
# this tool lets you select rectangle area of your screen [$mod+shift+y], and start recording that area.
# to stop press [$mod+shift+x] or use: swaycast stop

# stop script
PIDFILE="/tmp/wl-screenrec.pid"

if [[ "$1" == "stop" ]]; then
  PID=$(cat "$PIDFILE" 2>/dev/null)
  if [ -n "$PID" ]; then
    kill "$PID"
    notify-send -i media-playback-stop "Screencast stopped" "will now get converted and saved (may take some time)"
    rm -f "$PIDFILE"
  else
    notify-send -i dialog-error "No running Screencast found"
  fi
  exit 0
fi

# Try to get the XDG Videos directory using xdg-user-dirs
VIDEOS_DIR=$(xdg-user-dir VIDEOS 2>/dev/null)
if [ -z "$VIDEOS_DIR" ]; then
    VIDEOS_DIR="$HOME/Videos"
fi

SCREENCAST_DIR="$VIDEOS_DIR/screencasts"
mkdir -p "$VIDEOS_DIR"
DATE=$(date '+%Y-%m-%d_%H-%M-%S')
FILENAME="screencast_$DATE.mp4"
TARGET="$SCREENCAST_DIR/$FILENAME"

# Select recording area
GEOM=$(slurp)

# start recording (in the background)
wl-screenrec -g "$GEOM" -f "$TARGET" &
PID=$!

notify-send -i media-record "Screencast running" "stop with: [$mod+shift+x] or kill $PID"

# PID gets saved to be used for stop script
echo $PID > "$PIDFILE"

# Wait for recording to finish, then notify
wait $PID
notify-send -i document-save "Screencast saved" "$TARGET"
