#!/usr/bin/env bash
#
# swaycast - Screencast helper for Sway
#
# Copyright (C) 2025 joekamprad
#
# This script is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This script is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this script.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Author: Johannes Kamprad (joekamprad)
#

# needed packages: `sudo pacman -Syu --needed slurp wl-screenrec xdg-user-dirs`
# wl-screenrec currently only in AUR will be added to EndeavourOS repo in case of release
# this tool lets you select rectangle area of your screen [$mod+shift+y], and start recording that area. 
# to stop press [$mod+shift+x] or use: swaycast stop

# stop script
PIDFILE="/tmp/wl-screenrec.pid"

if [[ "$1" == "stop" ]]; then
  PID=$(cat "$PIDFILE" 2>/dev/null)
  if [ -n "$PID" ]; then
    kill "$PID"
    notify-send -i media-playback-stop "Screencast stopped"
    rm -f "$PIDFILE"
  else
    notify-send -i dialog-error "No running Screencast found"
  fi
  exit 0
fi

# screencast start part
VIDEOS_DIR=$(xdg-user-dir VIDEOS 2>/dev/null)
if [ -z "$VIDEOS_DIR" ]; then
  VIDEOS_DIR="$HOME/Videos"
fi

DIR="$VIDEOS_DIR/screencasts"
mkdir -p "$DIR"
FILENAME="screencast_$(date '+%Y-%m-%d_%H-%M-%S').mp4"
TARGET="$DIR/$FILENAME"

# Select recording area
GEOM=$(slurp)

# start recording (in the background)
wl-screenrec -g "$GEOM" -f "$TARGET" &
PID=$!

notify-send -i media-record "Screencast running" "stop with: screencast-select stop or kill $PID"

# PID gets saved to be used for stop script
echo $PID > "$PIDFILE"
