#!/usr/bin/env bash
#
# screenshot_all - Screenshot helper for Sway
#
# Copyright (C) 2025 Johannes Kamprad
#
# This script is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This script is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this script.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Author: Johannes Kamprad (joekamprad)
#

# needed packages: `sudo pacman -Syu --needed grim xdg-user-dirs`
# this tool creates a screenshot of all your screens in one picture, 

SCREENSHOT_DIR="$(xdg-user-dir PICTURES)/screenshots"
DATE=$(date '+%Y-%m-%d_%H-%M-%S')
FILENAME="screenshot_$DATE.png"
FILEPATH="$SCREENSHOT_DIR/$FILENAME"

mkdir -p "$SCREENSHOT_DIR"
grim "$FILEPATH"
notify-send "Screenshot created" "here: $FILEPATH" -i "$FILEPATH"
