#!/bin/bash

SCREENSHOT_DIR="$(xdg-user-dir PICTURES)/screenshots"
DATE=$(date '+%Y-%m-%d_%H-%M-%S')
FILENAME="screenshot_$DATE.png"
FILEPATH="$SCREENSHOT_DIR/$FILENAME"

mkdir -p "$SCREENSHOT_DIR"
grim "$FILEPATH"
notify-send "Screenshot erstellt" "Hier: $FILEPATH" -i "$FILEPATH"
